-- Seed blog posts for Special Academy
-- Run this after running blog-migration.sql

insert into blog_posts (title, slug, content, excerpt, author, image, status, tags, published_at) values

(
  'Top 10 Tips to Crack the Cadet College Entrance Exam',
  'cadet-college-entrance-exam-tips',
  '<h2>Start Early, Plan Smart</h2><p>The journey to securing a seat in a prestigious cadet college begins long before the exam date. Starting your preparation at least 6-8 months ahead gives you the advantage of thorough coverage without last-minute cramming.</p><h2>1. Understand the Exam Pattern</h2><p>Every cadet college exam follows a specific pattern. Generally, they include sections on Mathematics, English, General Knowledge, and IQ/Intelligence tests. Knowing the weightage of each section helps you allocate your time effectively.</p><h2>2. Build a Strong Foundation in Mathematics</h2><p>Mathematics carries significant weight in most cadet entrance exams. Focus on:</p><ul><li>Arithmetic: percentages, ratios, averages</li><li>Algebra: equations, inequalities</li><li>Geometry: angles, triangles, circles</li><li>Data interpretation: graphs, charts</li></ul><h2>3. Strengthen Your English</h2><p>Grammar, vocabulary, and comprehension are tested thoroughly. Read newspapers daily, maintain a vocabulary journal, and practice writing essays on common topics.</p><h2>4. Stay Updated with Current Affairs</h2><p>General Knowledge and current affairs sections require regular reading. Subscribe to a monthly GK digest and follow reputable news sources.</p><h2>5. Practice IQ and Reasoning</h2><p>Intelligence tests assess logical reasoning, pattern recognition, and problem-solving ability. Dedicate 30 minutes daily to puzzle-solving and mental ability exercises.</p><h2>6. Take Mock Tests Seriously</h2><p>Mock tests simulate the real exam environment and help you manage time effectively. At Special Academy, our students take weekly mock tests followed by detailed performance analysis.</p><h2>7. Focus on Physical Fitness</h2><p>Cadet colleges assess physical fitness too. Include regular exercise, running, and outdoor activities in your daily routine.</p><h2>8. Develop Discipline and Routine</h2><p>A disciplined daily routine is the hallmark of a successful cadet. Wake up early, study at fixed hours, and maintain a balanced schedule.</p><h2>9. Seek Guidance from Experienced Mentors</h2><p>Our faculty at Special Academy includes retired military officers and subject experts who provide personalized guidance to every student.</p><h2>10. Stay Confident and Positive</h2><p>Believe in yourself. The journey may be challenging, but with determination and the right preparation strategy, success is inevitable.</p><p><strong>Special Academy</strong> has been preparing future cadets since 2010. Join our program and take the first step toward your dream cadet college.</p>',
  'Proven strategies and expert tips to help you prepare effectively for cadet college entrance examinations. From study plans to mock tests, we cover everything.',
  'Special Academy',
  'https://images.unsplash.com/photo-1523050854058-8df90110c7f1?w=800&q=80',
  'published',
  '["cadet preparation", "exam tips", "study guide", "entrance exam"]',
  now() - interval '3 days'
),

(
  'A Day in the Life of a Cadet: What to Expect at Cadet College',
  'day-in-life-cadet-college',
  '<h2>Life at Cadet College: A Transformative Experience</h2><p>Cadet college life is unique, combining rigorous academics with military-style discipline and character development. Understanding what to expect helps students prepare mentally and emotionally for this transformative journey.</p><h2>Early Morning: The Dawn Call</h2><p>The day typically begins at 5:00 AM with a wake-up call. Cadets have 10 minutes to freshen up and assemble for physical training. Punctuality is non-negotiable.</p><h2>Physical Training (6:00 AM - 7:00 AM)</h2><p>Morning PT includes running, calisthenics, drill practice, and obstacle course training. This builds stamina, strength, and team spirit.</p><h2>Breakfast and Personal Hygiene (7:00 AM - 8:00 AM)</h2><p>A nutritious breakfast is followed by time for showering, room cleaning, and uniform preparation. Cadets learn the importance of personal grooming and maintaining a tidy living space.</p><h2>Academic Classes (8:00 AM - 1:00 PM)</h2><p>Five periods of academic instruction cover Mathematics, English, Science, Social Studies, and GK. The student-to-teacher ratio is kept small for personalized attention.</p><h2>Lunch and Rest (1:00 PM - 2:00 PM)</h2><p>A well-balanced lunch is followed by a short rest period.</p><h2>Extracurricular Activities (2:00 PM - 4:00 PM)</h2><p>Cadets engage in sports, hobby clubs, debate, music, and other activities that develop leadership and teamwork skills.</p><h2>Study Time (4:00 PM - 6:00 PM)</h2><p>Supervised self-study sessions help cadets complete assignments and revise lessons. Teachers are available for doubt clearance.</p><h2>Evening Activities (6:00 PM - 8:00 PM)</h2><p>Cultural programs, guest lectures, and recreational activities are held in the evening. This is also time for personal reading and relaxation.</p><h2>Dinner and Roll Call (8:00 PM - 9:30 PM)</h2><p>Dinner is followed by evening roll call and important announcements.</p><h2>Lights Out (10:00 PM)</h2><p>A good night''s sleep is essential. Cadets are expected to be in bed by 10:00 PM with lights out.</p><h2>The Transformation</h2><p>This structured routine may seem demanding at first, but it quickly becomes a way of life. Cadets emerge as confident, disciplined, and responsible individuals ready to take on any challenge.</p><p>At <strong>Special Academy</strong>, our preparation program mirrors this routine to ensure students are fully prepared for cadet college life.</p>',
  'Ever wondered what a cadet college daily routine looks like? From 5 AM PT to lights out at 10 PM, discover the structured life that builds future leaders.',
  'Special Academy',
  'https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?w=800&q=80',
  'published',
  '["cadet life", "daily routine", "cadet college", "discipline"]',
  now() - interval '7 days'
),

(
  'Why Physical Fitness Matters for Cadet College Admission',
  'physical-fitness-cadet-college',
  '<h2>Physical Fitness: A Key Criterion for Selection</h2><p>Many students focus solely on academic preparation but overlook the physical fitness component of cadet college admissions. This is a critical mistake.</p><h2>Why Cadet Colleges Emphasize Fitness</h2><p>Cadet colleges are not just academic institutions; they are training grounds for future military officers and leaders. Physical fitness is essential because:</p><ul><li>It builds stamina required for military training</li><li>It develops mental toughness and resilience</li><li>It teaches discipline through regular exercise</li><li>It promotes teamwork through sports and group activities</li><li>It ensures cadets can handle the physical demands of training</li></ul><h2>Common Physical Tests in Cadet Entrance Exams</h2><p>Most cadet college admissions include the following physical assessments:</p><h3>1. Running</h3><p>A 1.6 km run (approximately 1 mile) within a specified time. For boys under 15, the target is typically under 7 minutes; for girls, under 8 minutes.</p><h3>2. Push-ups</h3><p>Candidates are required to perform a minimum number of push-ups. Target: 15-20 for boys, 10-15 for girls.</p><h3>3. Sit-ups</h3><p>Abdominal strength is assessed through sit-ups. Target: 25-30 repetitions in one minute.</p><h3>4. Pull-ups (for boys) / Flexed Arm Hang (for girls)</h3><p>Upper body strength is measured through pull-ups or flexed arm hang.</p><h3>5. Chin-ups</h3><p>An additional measure of upper body strength.</p><h3>6. Long Jump</h3><p>Standing long jump measures explosive leg power. Target: 1.8-2.0 meters for boys.</p><h2>How to Prepare for the Physical Tests</h2><p>Start your physical preparation at least 3-4 months before the exam:</p><ul><li>Run every morning: start with 1 km, gradually increase to 2 km</li><li>Practice bodyweight exercises: push-ups, sit-ups, squats</li><li>Include stretching and flexibility exercises</li><li>Play outdoor sports: football, basketball, volleyball</li><li>Maintain a balanced diet rich in protein and vitamins</li></ul><h2>How Special Academy Prepares You</h2><p>At Special Academy, physical training is an integral part of our curriculum. Our experienced PT instructors design personalized fitness programs for each student, tracking progress through regular assessments.</p><p><strong>Remember:</strong> Physical fitness is not just about passing the test. It is about building a healthy lifestyle that will serve you throughout your cadet career and beyond.</p>',
  'Physical fitness is often the deciding factor in cadet college selection. Learn about the fitness tests, preparation strategies, and why it matters more than you think.',
  'Special Academy',
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80',
  'published',
  '["physical fitness", "cadet preparation", "fitness tips", "health"]',
  now() - interval '14 days'
),

(
  'How to Choose the Right Cadet Preparation Academy',
  'choose-right-cadet-preparation-academy',
  '<h2>Making the Right Choice for Your Future</h2><p>Choosing the right preparation academy is one of the most important decisions you will make on your journey to cadet college. With numerous options available, how do you select the best one?</p><h2>1. Track Record of Success</h2><p>Look for an academy with a proven track record. At Special Academy, 94% of our students successfully secure admission to prestigious cadet colleges. We are proud of our alumni who are now serving in various military and leadership positions.</p><h2>2. Experienced Faculty</h2><p>The quality of faculty makes all the difference. Our team includes retired military officers, subject matter experts, and experienced educators who understand the cadet exam pattern thoroughly.</p><h2>3. Comprehensive Curriculum</h2><p>The academy should offer a curriculum that covers all aspects of the entrance exam: Mathematics, English, General Knowledge, IQ tests, and Physical Training. A one-dimensional approach will not suffice.</p><h2>4. Mock Tests and Assessments</h2><p>Regular mock tests that simulate the actual exam environment are crucial. They help identify strengths and weaknesses, improve time management, and build exam confidence.</p><h2>5. Physical Training Program</h2><p>Since physical fitness is a key selection criterion, the academy must have dedicated physical training sessions with qualified instructors.</p><h2>6. Individual Attention</h2><p>Small batch sizes ensure that every student receives personalized attention. At Special Academy, we maintain an optimal student-to-teacher ratio.</p><h2>7. Past Results and Testimonials</h2><p>Speak to alumni and parents. Read testimonials and success stories. A good academy will have a community of successful graduates who are happy to share their experiences.</p><h2>8. Location and Facilities</h2><p>Consider the location, classroom facilities, library resources, and sports infrastructure. A conducive learning environment contributes significantly to success.</p><h2>9. Admission Support</h2><p>The academy should guide students through the entire admission process, from form filling to interview preparation.</p><h2>10. Values and Culture</h2><p>The academy''s values should align with cadet college ethos: discipline, integrity, excellence, and service. These values should be evident in the academy''s daily operations.</p><p><strong>Special Academy</strong> has been the trusted choice for parents and students since 2010. Visit our campus, meet our faculty, and see for yourself why we are Nepal''s premier cadet preparation academy.</p>',
  'Selecting the right preparation academy can make or break your cadet college dream. Here is a comprehensive guide to making an informed decision.',
  'Special Academy',
  'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80',
  'published',
  '["cadet academy", "preparation guide", "education", "choosing academy"]',
  now() - interval '21 days'
),

(
  'The Importance of Discipline in a Student''s Life',
  'importance-of-discipline-for-students',
  '<h2>Discipline: The Foundation of Success</h2><p>Discipline is often misunderstood as restriction or punishment. In reality, discipline is the bridge between goals and accomplishment. For students aspiring to join cadet colleges, discipline is not just a virtue but a way of life.</p><h2>What is Discipline?</h2><p>Discipline is the practice of training yourself to follow rules, maintain order, and adhere to a code of behavior. It is self-control, responsibility, and the ability to do what needs to be done even when you don''t feel like doing it.</p><h2>Why Discipline Matters for Students</h2><h3>1. Academic Excellence</h3><p>Disciplined students consistently perform better academically. They follow a study routine, complete assignments on time, and prepare systematically for exams. At Special Academy, our structured programs instill this discipline from day one.</p><h3>2. Time Management</h3><p>Discipline teaches effective time management. Students learn to prioritize tasks, avoid procrastination, and make the most of every hour.</p><h3>3. Character Development</h3><p>Discipline builds character. It teaches integrity, honesty, and responsibility. These qualities are highly valued in cadet colleges and throughout life.</p><h3>4. Stress Management</h3><p>A disciplined routine reduces stress. When you have a clear plan and follow it consistently, there is less room for anxiety and last-minute panic.</p><h3>5. Health and Fitness</h3><p>Disciplined sleep schedules, regular exercise, and healthy eating habits contribute to physical and mental well-being.</p><h2>How to Cultivate Discipline</h2><ul><li>Set clear goals and break them into daily tasks</li><li>Create a daily routine and stick to it</li><li>Wake up early and go to bed at fixed times</li><li>Limit distractions: reduce screen time, social media</li><li>Practice self-accountability</li><li>Surround yourself with disciplined people</li></ul><h2>Discipline at Special Academy</h2><p>At Special Academy, discipline is woven into every aspect of our program. From punctual class attendance to uniform standards, from study schedules to physical training routines, we help students internalize discipline as a lifelong habit.</p><p>Our alumni often share that the discipline they learned at Special Academy became the foundation of their success in cadet college and beyond.</p><p><strong>Remember:</strong> Discipline is choosing between what you want now and what you want most.</p>',
  'Discipline is the bridge between goals and accomplishment. Learn why it is the most important quality for students and how to cultivate it in daily life.',
  'Special Academy',
  'https://images.unsplash.com/photo-1552763656-23ae8d3af63a?w=800&q=80',
  'published',
  '["discipline", "student life", "character building", "success tips"]',
  now() - interval '30 days'
);
